################################################################
#
# web访问端口号 约定：8088
#
################################################################
server:
  port: 8088                              # 端口号
  tomcat:
    uri-encoding: utf-8                   # 编码
  max-http-request-header-size: 80KB      # 请求头大小



################################################################
#
# 配置文件激活
#
################################################################
spring:
  profiles:
    active: prod,redis   # 切换到生产环境
  servlet:
    multipart:
      max-file-size: 51200            # 限制上传文件大小（500kb）
      max-request-size: 51200         # 限制请求大小（500kb）

################################################################
#
# mybatis 配置
#
################################################################
mybatis:
  type-aliases-package: com.imooc.pojo        # 所有POJO类所在路径
  mapper-locations: classpath:mapper/*.xml    # classpath就是指resources文件夹路径，告诉mybatis mapper文件的位置

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印sql语句
  global-config:
    db-config:
      # 配置主键策略：数据库自增（默认是雪花算法：ASSIGN_ID）
      # 雪花算法更适合分布式系统，但是在单体应用中，数据库自增更方便
      id-type: ASSIGN_UUID
  # 配置类型别名所对应的包
  # 处理Mapper.xml中的resultType，这样就可以直接使用类名作为别名，而不需要写全类名
#  type-aliases-package: com.imooc.pojo



################################################################
#
# knife4j 配置
#
################################################################
knife4j:
  enable: true
  setting:
    language: zh_cn
springdoc:
  api-docs:
    path: /v3/api-docs

################################################################
#
# Apple Sign In Configuration
#
################################################################
apple:
  auth:
    client-id: com.rise.liven.SwiftTeam       # 替换为实际的 App Bundle ID
    team-id: BP68XD27A7               # 替换为实际的 Team ID
    key-id: HKK4R8QVUA                 # 替换为实际的 Key ID
    private-key: |                      # 替换为实际的 Private Key
      -----BEGIN PRIVATE KEY-----
      MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgjP2mBfY2S+RyXp7Q
      tiQOgzXxESckYgBoxTBd9jTxsD2gCgYIKoZIzj0DAQehRANCAAQ/RJKrJWAUx3F5
      xcT3V00vBGH5Wq6gy6KAZXI7EjOtK0YoO+AerwEgh726xar6ZP9FoQ6Iiw5dwJIm
      WRFkFjZt
      -----END PRIVATE KEY-----
    redirect-uri: ${server.scheme:https}://${server.domain:localhost:8088}/auth/apple/callback