################################################################
#
# UAT环境配置
#
################################################################
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodie?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    username: root
    password: qianli01
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: UatHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
