################################################################
#
# web访问端口号 约定：8088
#
################################################################
server:
  port: 8088                              # 端口号
  tomcat:
    uri-encoding: utf-8                   # 编码
  max-http-request-header-size: 80KB      # 请求头大小



################################################################
#
# 配置数据源信息
#
################################################################
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodie?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    username: root
    password: qianli01
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认10分钟
      pool-name: DataSourceHikariCP   # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认30分钟
      connection-test-query: SELECT 1 # 测试SQL
  servlet:
    multipart:
      max-file-size: 51200            # 限制上传文件大小（500kb）
      max-request-size: 51200         # 限制请求大小（500kb）

################################################################
#
# mybatis 配置
#
################################################################
mybatis:
  type-aliases-package: com.imooc.pojo        # 所有POJO类所在路径
  mapper-locations: classpath:mapper/*.xml    # classpath就是指resources文件夹路径，告诉mybatis mapper文件的位置

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印sql语句
  global-config:
    db-config:
      # 配置主键策略：数据库自增（默认是雪花算法：ASSIGN_ID）
      # 雪花算法更适合分布式系统，但是在单体应用中，数据库自增更方便
      id-type: ASSIGN_UUID
  # 配置类型别名所对应的包
  # 处理Mapper.xml中的resultType，这样就可以直接使用类名作为别名，而不需要写全类名
#  type-aliases-package: com.imooc.pojo



################################################################
#
# knife4j 配置
#
################################################################
knife4j:
  enable: true
  setting:
    language: zh_cn
springdoc:
  api-docs:
    path: /v3/api-docs